### ISSUE TITLE
Unable to build on OSX 10.11.1

### ISSUE THREAD

**Issue by noizfactory** [stephen/airsonos#244]
I was unable to build on El Capitan. I'm attaching the debug log output. Can someone please help?

npm ERR! mdns@2.2.10 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the mdns@2.2.10 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

[npm-debug.log.txt](https://github.com/stephen/airsonos/files/46610/npm-debug.log.txt)

**Comment by ricosuave0922** [comment]
same problem here any fix?

**Comment by thomascjohnson** [comment]
Me too! I even tried using a docker... didn't work.

**Comment by ColinRioux** [comment]
I have a fix! Well at least this worked for me. I'll provide step by step on what I did.

First, I looked into issues with node-gyp. I first installed it using npm by doing `$ npm install -g node-gyp`.  
Next, I checked if `binding.gyp` was in my root folder (open terminal and do `$ ls`, if it's there then good!) Otherwise, in your root folder, create the binding.gyp like the default given [here](https://github.com/nodejs/node-gyp).   
Next, do `$ python --version` to check your python version. For node-gyp to work, 2.7.x is best. 3.x doesn't work to my knowledge at least. If your version isn't 2.7.x, go [here](https://www.python.org) and download 2.7.10 for mac. Follow the instructions. Then re-open terminal and do `$ python --version` and make sure it is 2.7.10. 

From this point, write `$ which python` to find out where python is located. It should be in `/Library/Frameworks/...`. Then open the `~/.bash_profile` or `~/.bashrc` file and add the following lines: 
```
PYTHON=$PYTHON:(insert here the directory given at "which python")
export PYTHON
```
Then in terminal type `$ source ~/.bash_profile` or `$ source ~/.bashrc`. Now we have successfully setup python.

After, we must update the npm config as well to support this. Write the following commands into terminal:
```
$ npm config set python (insert here the directory given at "which python")
$ npm config set save=true
$ npm config set save-exact=true
$ npm config get 
```
The final line is just to make sure the settings were inputted into the config.

The final step (you may of have to earlier) is to make sure you have XCode **AND** XCode Command Line Tools installed. If you don't know how, first install the latest version of XCode from the app store. Next in terminal type `$ xcode-build --install`. After it has installed make sure to agree to the license by typing `$ xcode-build --license`.

At this point you should have all of the essential tools to try installing airsonos or any other npm packages that require node-gyp. *However, if you are currently in the same boat as I was, please install node-gyp install like so:*   
In terminal write:
```
$ npm install -g node-gyp-install
$ node-gyp-install
$ npm install -g airsonos
```
Essentially what [node-gyp-install](https://www.npmjs.com/package/node-gyp-install) does is manually install all of the node/iojs header files that are needed for node-gyp to work properly. After I did, as a wrap-up, I had no issue installing airsonos/mdns/all of those npm packages that depend on node-gyp. 

This ends my fix. Currently I'm still getting the bug where it either hangs on `$ airsonos` or it gives me an error regarding `bluebird`. I don't have fixes for that but hopefully soon.

**Comment by ricosuave0922** [comment]
I ended up getting it to work without all that hastle. Ill try to backtrack and figure out what i had to do to install it. If i remember correctly, manually installing it rather than using npm was the solution.

**Comment by ColinRioux** [comment]
Essentially my way is doing it involving npm. Your way is very promising as well, and I agree is probably easier. However, my fix works with all npm packages that require `node-gyp rebuild`. And example would be mdns.

**Comment by benzwu** [comment]
after all this time... I can't make it work. Now thansk to @ColinRioux, it works now. Thanks bro.

just these 3 lines, voilà!

    $ npm install -g node-gyp-install
    $ node-gyp-install
    $ npm install -g airsonos

**Comment by benzwu** [comment]
I have found bluebird error as well on my home setup (thru sonos bridge) but not on my office setup (wired).


    /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:677
                throw e;
                      ^
    Error: Method Not Allowed
        at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)

**Comment by ColinRioux** [comment]
I am receiving this error as well... probably first step to try is to unplug the bridge and link a speaker via ethernet (to the back of your router).

If that doesn't work, its best to watch the issues page for possible fixes from people.

**Comment by noizfactory** [comment]
Thanks for the solutions guys! I'll give it a go this weekend again. It
seems like post build, there's still some issue connecting to the speakers?

**Comment by benzwu** [comment]
the bridge is the culprit. after removing the bridge out of the equation, it works again.

**Comment by noizfactory** [comment]
This is great! It installed perfectly after following Colin's instructions. One additional step - *if you get an error* regarding connection reset then you need to [change](http://stackoverflow.com/a/18428563) npm configs to use http instead of https:

`npm config set registry http://registry.npmjs.org/`

Ironically, SONOS is launching apple music on beta tomorrow. But this is better! :) Cheers everyone for all the help (and to the author for this awesome hack)!

**Comment by fourmind** [comment]
@ColinRioux, beautiful! Thanks so much!

I couldn't get `$ xcode-build --install` to work, but was able to download the Xcode Command Line tools and install them separately. For those who hit that, open Xcode, then from the Xcode menu, go to Open Developer Tool and choose More developer tools... to go to a download site.

**Comment by maelcum** [comment]
Getting same error as bezwu and ColinRioux from bluebird when SONOS bridge is installed. Without Bridge no problems but ... alas neither speakers, since those are addressed via the bridge.
Is there a way to exclude the detection of the bridge in bluebird? 
Or is my only change to switch the speakers to WLAN instead of SONOSNet. I preferred the latter as the WiFis around me are disturbing WLAN operations (and thus the speaker operations).

**Comment by olets** [comment]
I didn't have these installation problems, but @ColinRioux did help me realize I didn't have `node-gyp` installed. This was causing other problems, because things were getting stuck in a temp directory.
