### ISSUE TITLE
OS X 10.10 Problems

### ISSUE THREAD

**Issue by satan87** [stephen/airsonos#27]
I try airsonos on the beta of yosemite. The software can see my sonos but i got only background noise.
Also, i cannot make the real sonos app works again.

On my terminal i got 
Searching for Sonos devices on network...
Setting up AirSonos for Living Room {192.168.1.93:1400}

and on the sonos app i go
Unable to play 'AirSonos' - unable to connect to 192.168.1.53:8000

ps :
1.93 is my sonos play5
1.53 is my mac
Any idea ?

**Comment by ahoernecke** [comment]
I was having the same problem (OS X Yosemite). It seems that my system includes an IP address of 127.94.0.1 for the loopback device, and this is what is being picked up by the ip.address() function being used to set the IP (as @stephen noted earlier). 

I tweaked airsonos to add the option to specify an interface (i.e. en0) to bind to instead of blindly relying on ip.address(). This seems to have fixed my issues and I have submitted pull requests for these tweaks. I'm not really a node developer so you may want to do this different, but at the least it seems to identify the issue and provide an option for solving it.

See Pull request #98

**Comment by Nabk6** [comment]
Hey I'm on yosemite and every time i try to use airsonos it says 

Voop:~ noahabecassis$ airsonos
Searching for Sonos devices on network...
Setting up AirSonos for Noah's Sonos {IP}

And then displays my sonos in the volume options, but when i click it and try to play sound it just lags and doesn't work. Any idea on what I can do?

**Comment by LinusU** [comment]
@Nabk6 which version of Node.js are you running? `0.12.x` currently dosen't work, see #113 for more info.

**Comment by Noahabk6** [comment]
Hey, had to make a new account but i am running Node v.10.3.3

**Comment by Noahabk6** [comment]
^ @LinusU
